"""empty message

Revision ID: 4972914f0e93
Revises: e41efa2f15ea
Create Date: 2026-07-21 18:41:46.985721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4972914f0e93'
down_revision: Union[str, Sequence[str], None] = 'e41efa2f15ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chain_completion_date', 'chain_completion_history', ['chain_id', 'completion_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chain_completion_date', 'chain_completion_history', type_='unique')
    # ### end Alembic commands ###
