"""empty message

Revision ID: 5fd246bfab65
Revises: cf82d43afd0e
Create Date: 2026-05-26 04:20:23.224843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5fd246bfab65'
down_revision: Union[str, Sequence[str], None] = 'cf82d43afd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_provider_id'), 'user', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_provider_id'), table_name='user')
    op.drop_column('user', 'provider')
    op.drop_column('user', 'provider_id')
    # ### end Alembic commands ###
