"""empty message

Revision ID: ac183d61e507
Revises: 8786e65f1083
Create Date: 2026-07-09 15:06:20.362704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac183d61e507'
down_revision: Union[str, Sequence[str], None] = '8786e65f1083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', name='chainfrequency'), nullable=False),
    sa.Column('frequency_per_week', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_completion_history',
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HOLIDAY', 'SUCCESS', 'FAILURE', name='chaincompletionstatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_completion_history_id'), 'chain_completion_history', ['id'], unique=False)
    # ### end Alembic commands ###

    op.create_check_constraint(
        "ck_chain_frequency_per_week_range",
        "chain",
        "frequency_per_week BETWEEN 1 AND 7",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_completion_history_id'), table_name='chain_completion_history')
    op.drop_table('chain_completion_history')
    op.drop_table('chain')
    # ### end Alembic commands ###
