"""empty message

Revision ID: b630c81fcde5
Revises: 4972914f0e93
Create Date: 2026-08-12 09:59:13.811501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b630c81fcde5'
down_revision: Union[str, Sequence[str], None] = '4972914f0e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chain_completion_history_id'), table_name='chain_completion_history')
    op.drop_table('chain_completion_history')
    op.create_table('chain_history',
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HOLIDAY', 'SUCCESS', 'FAILURE', name='chainhistorystatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'completion_date', name='uq_chain_completion_date')
    )
    op.create_index(op.f('ix_chain_history_id'), 'chain_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_completion_history',
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('HOLIDAY', 'SUCCESS', 'FAILURE', name='chaincompletionstatus'), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], name=op.f('chain_completion_history_chain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chain_completion_history_pkey')),
    sa.UniqueConstraint('chain_id', 'completion_date', name=op.f('uq_chain_completion_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_chain_completion_history_id'), 'chain_completion_history', ['id'], unique=False)
    op.drop_index(op.f('ix_chain_history_id'), table_name='chain_history')
    op.drop_table('chain_history')
    # ### end Alembic commands ###
