"""empty message

Revision ID: e41efa2f15ea
Revises: 11eb0326d48c
Create Date: 2026-07-21 07:19:19.557693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e41efa2f15ea'
down_revision: Union[str, Sequence[str], None] = '11eb0326d48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authprovider = postgresql.ENUM(
        "GOOGLE",
        "GITHUB",
        "APPLE",
        name="authprovider",
    )
    authprovider.create(op.get_bind(), checkfirst=True)

    op.add_column('chain', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('GOOGLE', name='authprovider'),
               existing_nullable=False,
        postgresql_using="provider::authprovider",
    )
    op.alter_column('user', 'registered_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'registered_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'provider',
               existing_type=sa.Enum('GOOGLE', name='authprovider'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('chain', 'deleted')
    # ### end Alembic commands ###
